### ISSUE TITLE
Plain request, with URL formatting

### ISSUE THREAD

**Issue by lowjoel** [andyjeffries/flexirest#11]
Is there any way to support plain requests while doing URL substitutions? I'd like to do something like this:

```ruby
plain_request('courses/assessment/programming_evaluations/:id/package', id: id)
```
(from https://github.com/Coursemology/evaluator-slave/blob/master/lib/coursemology/evaluator/models/programming_evaluation.rb)

and URL substitution will replace id with the variable. Plain requests currently do not support that (all URLs are used verbatim), is there any reason for that?

I'm not directly returning the contents of that endpoint within my response for the rest of the record because that's a blob. (not supporting streamy response parsing is a separate issue...)

**Comment by andyjeffries** [comment]
There isn't at the moment, but I'd happily accept a pull request to support it. From memory - plain request functionality was added for a single specific need while at Which and one I haven't needed to repeat.

**Comment by lowjoel** [comment]
Yes, in my case, it's because of that one resource that shouldn't (can't?) be in the main response.

If anyone's interested, my current hack is:

```ruby
  # Performs a plain request.
  #
  # @param [String] url The URL to request.
  # @param [Hash] params The parameter to be part of the request.
  # @return [String] The response body.
  def plain_request(url, params = {})
    request = Flexirest::Request.new({ url: url, method: :get, options: { plain: true } },
                                     self.class)
    request.call(params)
  end
```

**Comment by jp3hou** [comment]
Thanks for the hack @lowjoel! I had this same issue.

**Comment by andyjeffries** [comment]
Given that you both have this problem, I'd like to fix it.  I've just committed a new version that supports URL parameter replacement in _request and _plain_request.  Please test v1.2.16 and see if it does what you'd expect.

**Comment by lowjoel** [comment]
Awesome, thanks! It works great.
