### ISSUE TITLE
Flexirest::ResponseParseException

### ISSUE THREAD

**Issue by davidtolsma** [andyjeffries/flexirest#13]
I am calling a url that returns json. The format of the URL has /familiies.json as the end point. The json is valid, but I'm getting a Flexirest::ResponseParseException when it's called. 

The response header has Content-Type = text/plain is that reason?

When verbose! is enabled, the json is shown in log, with a status of 200

```
Flexirest Verbose Log:
  Request
  >> GET /weblib/prod/catalog/families.json HTTP/1.1
  >> Accept : application/hal+json, application/json;q=0.5
  >> Content-Type : application/x-www-form-urlencoded
  >> Body:

  Response
  << Status : 200
  << date : Tue, 02 Feb 2016 21:52:56 GMT
  << server : Apache
  << last-modified : Tue, 02 Feb 2016 02:25:54 GMT
  << etag : "4d84d7-20f2-3886d080"
  << accept-ranges : bytes
  << content-length : 8434
  << connection : close
  << content-type : text/plain
  << Body:
{"families":{ <i've truncated the rest of the response>
```

Then after the json is shown i get this

```
  Flexirest (142.0ms) ProductFamily#all
Completed 500 Internal Server Error in 149ms (Flexirest: 142.0ms for 1 calls | ActiveRecord: 0.0ms)

Flexirest::ResponseParseException (Flexirest::ResponseParseException):
```

The model "**product_family.rb**"  has the base_url defined, and a get :all, "/families.json"

When i put this url in postman or the web browser, it does display the json.

What is Flexirest expecting that this if failing?

**Comment by andyjeffries** [comment]
The server is returning `text/plain` as the `content-type`, so Flexirest doesn't know that it's JSON coming back...  I don't know if you (or your company) wrote the server, but that should be corrected.

If that's not possible, you can use an `after_request` callback to add the correct `Content-type` header in...

**Comment by davidtolsma** [comment]
Thanks, that worked.
