### ISSUE TITLE
Question: Is it possible to use has_many association with nested JSON response?

### ISSUE THREAD

**Issue by lewispb** [andyjeffries/flexirest#20]
I use the `has_many` feature which is great but is it possible to chain has_many definitions in a class when the JSON response is deeply nested?

**Comment by andyjeffries** [comment]
I wonder if I'm misunderstanding the question.  There's no need for chained definitions because the `has_many` instantiates the same or another class, and that class can have its own `has_many` calls.  So there's no need for chaining.

**Comment by lewispb** [comment]
Thanks for getting back to me. You're right but the has many definition occurs as an option of the get / post etc class method in parent class. So I don't see how I could configure the child class to parse the JSON used to instantiate it to instantiate further child classes.

**Comment by andyjeffries** [comment]
Ahhh, you're right. Maybe then I need to rework it to also be a class method. Then whenever that method is called, it will look at the attributes, and instantiate them if required.  I'll have a play with this...

**Comment by lewispb** [comment]
That would be awesome :) thanks. If you want to put up your branch i'd be happy to take a look too.

**Comment by andyjeffries** [comment]
OK, have a look at https://github.com/andyjeffries/flexirest/tree/associations

In particular, the second code example : https://github.com/andyjeffries/flexirest/tree/associations#association-type-1---loading-other-classes

**Comment by andyjeffries** [comment]
@lewispb I don't know if you've seen the above, but as the tests pass and it's backwards compatible with the previously published interfaces, I'm likely to merge it to master and release it anyway.  So, I'll give you a day or so, if I don't hear back then I'll just release it.

**Comment by lewispb** [comment]
That looks great @andyjeffries sorry for the delay in getting back to you. :+1:
