### ISSUE TITLE
Duplicated hash keys and values

### ISSUE THREAD

**Issue by JurgenJocubeit** [andyjeffries/flexirest#21]
I have the Person resource which inherits from Flexirest::Base.

I invoke the `#create` method on the class instance as per the README:

```ruby
@person = Person.create(
  first_name: “John”, 
  last_name: “Smith"
)
```

At the (Rails) server when I inspect the params, I get the following:

```ruby
{“first_name”=>”John”, “last_name”=>”Smith”, “controller”=>”persons”, “action”=>”create”, 
“person”=>{“first_name”=>”John”, “last_name”=>”Smith”}}
```

Can you see the duplicated keys and values?

I’m wondering how I can avoid this?

I find that the strong parameters then causes `first_name` and `last_name` keys to be rejected (warning in log output) because I have: 

```ruby
params.require(:person).permit(:first_name, :last_name)
```

Any clues how I can have just the `plan` hash, or even just the individual key pairs (one or the other)?

If I use:

```ruby
params.permit(:first_name, :last_name)
```

Then I get a warning about `plan` being rejected.

I am running Rails 5.0.0.beta2 and Ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15].

**Comment by andyjeffries** [comment]
This must be a Rails Beta problem.  I've just done this outside of Rails, with the latest version of Flexirest (v1.3.3) connecting to a Mockbin request and it worked fine.

```ruby
class Person < Flexirest::Base
  base_url "http://mockbin.org"
  verbose!

  post :create, "/bin/00cb71c2-6444-40d8-add7-f86d737b2016"
end

@person = Person.create(
  first_name: "John", 
  last_name: "Smith"
)
```

The log file shows this (note the request body):

```
  Flexirest Person#create - Requesting http://mockbin.org/bin/00cb71c2-6444-40d8-add7-f86d737b2016
Flexirest Verbose Log:
  Request
  >> POST /bin/00cb71c2-6444-40d8-add7-f86d737b2016 HTTP/1.1
  >> Accept : application/hal+json, application/json;q=0.5
  >> Content-Type : application/x-www-form-urlencoded
  >> Body:
first_name=John&last_name=Smith      <-------- LOOK HERE
  Response
  << Status : 200
  << date : Tue, 08 Mar 2016 09:07:15 GMT
  << content-type : text/html; charset=utf-8
  << transfer-encoding : chunked
  << connection : keep-alive
  << set-cookie : __cfduid=d83290eb1d0244377049f1449a9cfc01f1457428035; expires=Wed, 08-Mar-17 09:07:15 GMT; path=/; domain=.mockbin.org; HttpOnly
  << vary : X-HTTP-Method-Override, Accept-Encoding
  << etag : W/"14-H4mTA7klBR8HrXUJDd41+Q"
  << via : 1.1 vegur
  << server : cloudflare-nginx
  << cf-ray : 280522c77ce10a7e-LHR
  << Body:
{
"hello": "world"
}
```

**Comment by andyjeffries** [comment]
Can you reproduce it in your application just using a curl command line, if so, might be worth reporting it as a Rails 5 bug?

**Comment by andyjeffries** [comment]
I'm closing this issue as I can't reproduce it and there's been no response.
