### ISSUE TITLE
JSON Root

### ISSUE THREAD

**Issue by dsarhadian** [andyjeffries/flexirest#26]
Does flexirest support parsing a root object in a JSON response like so?

`{ coupon : { name: "test", discount: 20 } }`

Right now in my code, I have to do 
`@coupon = Coupon.find(params[:id])
@coupon = @coupon.coupon`

I was wondering if there is a simpler way to handle this.

Thanks!

**Comment by andyjeffries** [comment]
Good request! This was an available feature for XML responses with `ignore_xml_root`, but was never implemented for JSON responses. I've just pushed a new version out with this feature (v1.3.3).

https://github.com/andyjeffries/flexirest#root-element-removal
