### ISSUE TITLE
ResultIterator method missing

### ISSUE THREAD

**Issue by lewispb** [andyjeffries/flexirest#28]
When using the new `has_many` feature with deeply nested models I would see the following error:

```
NoMethodError:
        undefined method `[]=' for #<Flexirest::ResultIterator:0x007fa4bf231e08>
```

Adding the following monkey patch solved the issue. Do you see any issue with adding this to the class?

```
module Flexirest
  class ResultIterator

    def []=(key, value)
      @items[key] = value
    end

  end
end
```

**Comment by andyjeffries** [comment]
Could you possiby create a failing spec in a branch?  That would help me visualise the problem.

**Comment by lewispb** [comment]
Thanks for looking at this. Sorry it's not the tidiest but this was just something I put together quickly:

https://github.com/lewispb/flexirest/blob/method-missing-test/spec/lib/integration_spec.rb

**Comment by andyjeffries** [comment]
Thanks for that. Let's continue the discussion in #29.

**Comment by andyjeffries** [comment]
v1.3.5 release containing this fix.  Thanks :-)
