### ISSUE TITLE
`attr` returning `nil`

### ISSUE THREAD

**Issue by execjosh** [andyjeffries/flexirest#32]
Thank you for this wonderful gem!  I was hoping you could help me figure out this little problem I'm having.  I'm probably just not understanding something or doing it wrong!

# Problem

Using `attr` seems to block getting actual value.  

```ruby
class Community < Flexirest::Base
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr :id

  get :find, '/communities', fake: ->(req) { req.prepare_params; [{id: req.get_params[:id]}] }
end
```

# (My) Expected Result

I expected to be able to access the `attr` `id`.

```ruby
>> Community.find(1).first
=> #<Community id: 1>
>> Community.find(1).first.id
=> 1
```

# Actual Result

Instead, I get `nil` returned.

```ruby
>> Community.find(1).first
=> #<Community id: 1>
>> Community.find(1).first.id
=> nil
```

**Comment by andyjeffries** [comment]
Why do you have attr in there at all? It's not needed, the gem will automatically respond to any attributes assigned to (either if you manually create an object or after an api response). Let me know what you're trying to do and I'll help more if I can.

**Comment by execjosh** [comment]
Thank you for your time :smile: 

I hope this conveys my situation:

1) The backend API is in heavy development
2) As such, the actual names of attributes in the response are fluid (unfortunate, I know; but, that is the situation)
3) When I do `Community.new`, there are no attributes, which causes an empty form with `form_for`
4) In order to provide attributes, my first thought was to use `attr`

Is there a better way to accomplish this?

**Comment by execjosh** [comment]
> the gem will automatically respond to any attributes assigned to (either if you manually create an object or after an api response)

Missed that...  The API is not really `fake`-able at this point; so, I'm ignoring it.  I want to pretend that the attributes are there in order to create forms, using `Community.new` and `form_for`.

**Comment by andyjeffries** [comment]
So you can either pass default attributes in to .new or. Create a temporary initialiser that assigns them to the @_attributes hash. I'm at a conference at the moment but can reply with code samples later today.

**Comment by andyjeffries** [comment]
OK, I'm back at home now, so can code up the two suggestions to demonstrate the solutions.  The first one is just to pass in default attributes when creating the object:

```ruby
class MyController < ApplicationController
  def new
    @community = Community.new(id: nil)
  end
end
```

The alternative is to define an initializer on `Community` so all new instances automatically get the correct set of attributes ready for use in `form_for`:

```ruby
class Community < Flexirest::Base
  # Mapping methods

  def initialize(fields)
    super {id: nil}.merge(fields)
  end
end

**Comment by execjosh** [comment]
D'oh! /facepalm

I don't know why I was so locked on to `attr`; but, `initialize` is exactly what I want.  This completely solves my problem.  Thank you very much for taking the time to help.

Going back to the title of this issue, though, is this the expected behaviour if there were to be an `attr`?

**Comment by andyjeffries** [comment]
Yes, I would expect that behaviour. The reason is that Flexirest works by using method_missing to look up the attributes from its internal `@attributes` hash. If you use `attr`, that defines methods to store and retrieve values in the specific `@id` instance variable which none of the rest of Flexirest is expecting (it's expecting them to be in `@attributes`). So, yes it's expected (and would be a considerable rewrite to work around).

I'll close this issue now that I know your problem is solved. You're welcome for the help.
