### ISSUE TITLE
Use CanCan with Flexirest

### ISSUE THREAD

**Issue by rui-ribeiro** [andyjeffries/flexirest#36]
Hi,

I am using Flexirest with CanCan(Can) in my application and every thing works fine until today, I was checking the permission likes this:

```ruby
can? :update, User
```

And that works fine, but know I want to be more specific, like you can only edit your own user so I added to ability.rb:

```ruby
can :update, User, id: user.id 
```

But When I try to do:

```ruby
can? :update @user
```

Rails returns:
```ruby
TypeError - no implicit conversion of nil into Integer:
  cancancan (1.13.1) lib/cancan/ability.rb:379:in `possible_relevant_rules'
  cancancan (1.13.1) lib/cancan/ability.rb:367:in `relevant_rules'
  cancancan (1.13.1) lib/cancan/ability.rb:386:in `relevant_rules_for_match'
  cancancan (1.13.1) lib/cancan/ability.rb:67:in `block in can?'
  cancancan (1.13.1) lib/cancan/ability.rb:66:in `can?'
  cancancan (1.13.1) lib/cancan/controller_additions.rb:380:in `can?'
  actionpack (4.2.5.1) lib/abstract_controller/helpers.rb:67:in `can?'
```

When I use a ActiveRecord Object, I don´t have that problem.
Can you give me some hints ?

**Comment by andyjeffries** [comment]
Out of interest, does it go away if you define this on your model:

```ruby
class RuiModel < Flexirest::Base
  # ...

  def id
    @attributes[:id]
  end
end
```

I don't use cancan, so I'm trying to guess and go through their code to see what could be happening. If not, if you are able to make a small test app and shove it on GitHub I can try to debug it.

**Comment by andyjeffries** [comment]
What it seems to be doing is calling some method on the object (that it wants an ID back from) which is returning Nil on your object. I don't know if it's calling `#id` or something else though.

**Comment by andyjeffries** [comment]
You might be better off raising an issue on CanCanCan https://github.com/CanCanCommunity/cancancan/issues to ask what methods a Plain Old Ruby Object (PORO) needs to implement in order to support the shorter `@variable` check?  Then I can look at implementing it or at least documenting it here.

**Comment by rui-ribeiro** [comment]
This don´t work, unfortunally.
```ruby
  def id
    @attributes[:id]
  end
```

I have tried different approaches what I think that is happening is the following. 
```ruby
#...
def possible_relevant_rules(subject)
  #... 
  positions = @rules_index.values_at(subject, *alternative_subjects(subject))
end
```

If you pass only **alternative_subjects(subject)** to values_at everything works like a charm. So, I started to clean up my subject to see what is creating the conflict and I end up with a clean instance of the Model and the problem persists.

So I started to pass thinks like nil, [], {hash: { inside_hash: {} }} to see if the error happens, but without success to replicate the error. 

What function values_at  does is "Return an array containing the **values associated with the given keys**.". 

I start thinking that maybe "values_at" found a associated value but can´t return them but I didn´t get success with this approach either. 

I think the problem is not what Flexirest object don´t have is what they have.

Maybe is worth saying that my models inherits all from this BaseAdapter:

```ruby
class BaseAdapter < Flexirest::Base
  perform_caching false
  include ActiveModel::Conversion
  include ActiveModel::Validations
end
```

**Comment by rui-ribeiro** [comment]
Demo app:

https://github.com/brunomiguelpinto/SampleApp

**Comment by rui-ribeiro** [comment]
If found the I use CanCanCan version **1.12.0** it works...

**Comment by andyjeffries** [comment]
Is that an older version or a newer version?

**Comment by rui-ribeiro** [comment]
Older version, they are currently at 1.13.1

**Comment by andyjeffries** [comment]
Then that may help narrow it down on their side...

**Comment by rui-ribeiro** [comment]
Yeah, I hope so.

Thanks for the quick support !

**Comment by andyjeffries** [comment]
No worries, sorry I can't help you with it further - but I don't use CanCanCan and don't know if I need to do anything to help support it. If you get any more details that can be added to the Flexirest documentation, let me know.

**Comment by create-renegr** [comment]
For your infos, this seems to be related: https://github.com/flexirest/flexirest/pull/99
