### ISSUE TITLE
Timeout settings not being respected

### ISSUE THREAD

**Issue by jesmith17** [andyjeffries/flexirest#40]
I am using flexirest to issue rest calls from inside the worker thread created by sneakers:run. 

I added debugging puts statements to the connection.rb class (in the post method) and can verify that my connection timeout setting is 60 seconds, but when I execute the code I am seeing it timeout in less than 2. 
Something about how flexirest is running when inside the sneakers thread is making the timeout settings be ignored, or at least that the best I can tell. I have verfiied that it's a Flexirest::Timeoutexecption that is being returned from the call. 

I know this is a weird setup, and it's possible that the sneakers side is really the problem, but I have exhausted my debugging ability trying to track this down.

**Comment by andyjeffries** [comment]
Sorry to pass you around, but if timeouts work in normal code, we do nothing different if it's being done in a Thread.  We use Faraday to set the timeouts, so if it's not working I'd recommend raising it up to them. Sorry I can't help you more.
