### ISSUE TITLE
Attribute parsing of dates isn't anchored and can't handle nil. Fails on certain dates and nil values.

### ISSUE THREAD

**Issue by mmealling** [andyjeffries/flexirest#41]
If a value contains a date that isn't completely parsable by Date it still triggers the regex and then fails. It also fails if the value is nil. Looking at where it's called in Flexirest::Request#new_object that regex is reparsed and called on every non-Hash/Array object which has to be non-optimal. Date parsing is also sensitive to timezone and other localizations that would affect the outcome.

Attribute parsing should be optional on a route so the caller can handle special cases.

**Comment by mmealling** [comment]
In Request#new_object:
```
      attributes.each do |k,v|
        k = k.to_sym
        overridden_name = select_name(k, overridden_name)
        if @method[:options][:lazy].include?(k)
            ...
        elsif v.is_a? Hash
            ...
        elsif v.is_a? Array
            ...
        else
          object._attributes[k] = parse_attribute_value(v)
        end
      end
      object.clean! unless object_is_class?
      object
    end
```
This appears to use a complex regex to test every attribute to see if it could be a date? Given how expensive regular expressions can be I think this should be an option.

**Comment by andyjeffries** [comment]
You're right, I agree.  I'll change it so that it maintains the current functionality, but is easily disabled with an option, but then re-enabled with an option per mapping.

**Comment by mmealling** [comment]
Sweet!

**Comment by andyjeffries** [comment]
All done and released as 1.3.16. Documented at https://github.com/andyjeffries/flexirest#automatic-conversion-of-fields-to-datedatetime (at some point I must break the documentation down more - it's crazy long now!)

**Comment by SeraphAdmin** [comment]
This works like a champ, btw. Thanks for fixing this so quickly!

**Comment by mmealling** [comment]
This works like a champ, btw. Thanks a lot for making the fix so quickly!

**Comment by andyjeffries** [comment]
You're welcome. Glad it works for you.
