### ISSUE TITLE
How to use pagination?

### ISSUE THREAD

**Issue by adisos** [andyjeffries/flexirest#5]
My code:
```
[1] pry(main)> Post.all.paginate(page: 1, per_page: 5)
  Flexirest Post:/posts?with_categories=true&with_tags=true - Trying to read from cache
  Flexirest Post#all - Etag cached copy found with etag W/"48c26506e97f78a13d739549acf973c1"
  Flexirest Post#all - Requesting http://api.local/v1/posts?with_categories=true&with_tags=true
  Flexirest Post#all - Etag copy is the same as the server
  Flexirest Post:/posts?with_categories=true&with_tags=true - Writing to cache
  Flexirest (3195.6ms) Post#all
=> nil
```

My model:
```
class Post < Base
  get :all, "/posts"
  get :find, "/posts/:id"

  before_request do |name, request|
    if name == :all
      request.get_params[:with_categories] = true
      request.get_params[:with_tags] = true
    end
  end
end
```

**Comment by andyjeffries** [comment]
What did `.all` return without the `.paginate`?  Do you have the `will_paginate` gem enabled in your project?

**Comment by adisos** [comment]
Yes, I have installed `will_paginate` gem. It works:
```
pry(main)> AdminUser.paginate(page: 1, per_page: 5)
  AdminUser Load (0.4ms)  SELECT  "admin_users".* FROM "admin_users" LIMIT 5 OFFSET 0
=> [#<AdminUser:0x0000000967cbc8
  id: 1,
  email: "admin@example.com",
  encrypted_password: "$2a$10$KUlxHvrohjwIRgndXwvVQucF341vTz00AVykslg5YCoVIvvecDQFe",
  reset_password_token: nil,
  reset_password_sent_at: nil,
  remember_created_at: Fri, 04 Dec 2015 02:05:48 UTC +00:00,
  sign_in_count: 1,
  current_sign_in_at: Fri, 04 Dec 2015 02:05:48 UTC +00:00,
  last_sign_in_at: Fri, 04 Dec 2015 02:05:48 UTC +00:00,
  current_sign_in_ip: "127.0.0.1",
  last_sign_in_ip: "127.0.0.1",
  created_at: Fri, 04 Dec 2015 02:05:08 UTC +00:00,
  updated_at: Fri, 04 Dec 2015 02:05:48 UTC +00:00>]
```

`.all` returns this:
pry(main)> Post.all
  Flexirest Post:/posts?with_categories=true&with_excerpt=true&with_tags=true - Trying to read from cache
  Flexirest Post#all - Etag cached copy found with etag W/"45af9945c68883afe7a5d00c5b81ea60"
  Flexirest Post#all - Requesting http://api.local/v1/posts?with_categories=true&with_excerpt=true&with_tags=true
  Flexirest Post#all - Etag copy is the same as the server
  Flexirest Post:/posts?with_categories=true&with_excerpt=true&with_tags=true - Writing to cache
  Flexirest (3064.9ms) Post#all
=> #<Post current_page: 1, posts: #<Flexirest::ResultIterator:0x00000006962cc8 @_status=nil, @_headers=nil, @items=[...]>, ETag: W/"45af9945c68883afe7a5d00c5b81ea60", Status: 200>

**Comment by andyjeffries** [comment]
From your output, your API is already returning a paginated object.

The `will_paginate` support is about faking pagination to an API that isn't paginated:

> If an API returns an **array of results** and you have will_paginate installed then you can call the paginate method to return a particular page of the results (note: this doesn't reduce the load on the server, but it can help with pagination if you have a cached response).
https://github.com/andyjeffries/flexirest#usage

Your response though is not an **array of results** (a Flexirest::ResultIterator), it's an object that contains a `current_page` and `posts` array (Flexirest::ResultIterator).  Therefore the `will_paginate` support can't paginate the object (as it only exists on Flexirest::ResultIterator).

Hope that makes things clearer.  This report doesn't express a bug though (the system shouldn't be doing anything here) so I'll close it.  Feel free to keep commenting though if it's not clear and I'll keep explaining.

**Comment by adisos** [comment]
I confirm, that I can use paginate on `Post.all.posts`. It's working.

But I think `paginate` method will change `per_page` and `page` params on request. So if I passed `paginate(page: 1, per_page: 15)` it will generate url like:
```
http://api.local/v1/posts?page=1&per_page=15
```

**Comment by andyjeffries** [comment]
No, the paginate method doesn't change anything on the request.  It's effectively just treating the ResultIterator as an array and then paginating it.  That's what the documentation means when it says that it doesn't affect load on the server.  If you make an API call that returns 1,000 posts then the server will still have to find and send 1,000 posts down the line, then the `will_paginate` stuff will just discard 980 of them to make your page of 20.  It's a convenience for the display, rather than than anything to do with the request.

The code for the method is reasonably short:

https://github.com/andyjeffries/flexirest/blob/master/lib/flexirest/result_iterator.rb#L70

In your case as your API is internally paginated, if you want a different page, you should pass that in during the request, something like `Post.all(current_page: 2)`.

**Comment by adisos** [comment]
Ahh, now it's clear to me. Thanks.

**Comment by andyjeffries** [comment]
You're welcome, happy to help :)
